# Generated by Django 4.1.1 on 2022-10-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favoriterecipe",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="incartrecipe",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="ingredientrecipe",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-created", "name"),
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("slug", "-created"),
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
        migrations.AlterModelOptions(
            name="tagrecipe",
            options={"ordering": ("-created",)},
        ),
    ]
