# Generated by Django 4.1.1 on 2022-10-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscribe",
        ),
    ]
