# Generated by Django 4.1.1 on 2022-09-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                upload_to="recipes/images/user_directory_path", verbose_name="image"
            ),
        ),
    ]
