# Generated by Django 4.1.1 on 2022-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Color in RGB #RRGGBB format",
                max_length=7,
                unique=True,
                verbose_name="color",
            ),
        ),
    ]
