# Generated by Django 4.1.1 on 2022-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="recipes/images/",
                verbose_name="image",
            ),
        ),
    ]
