# Generated by Django 4.1.1 on 2022-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_ingredientrecipe_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", through="recipes.TagRecipe", to="recipes.tag"
            ),
        ),
    ]
