# Generated by Django 4.1.1 on 2022-09-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_ingredientrecipe_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_recipes",
                to="recipes.recipe",
            ),
        ),
    ]
