# Generated by Django 4.1.1 on 2022-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_subscribe"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscribe",
            constraint=models.UniqueConstraint(
                fields=("author", "user"), name="unique_subscription"
            ),
        ),
    ]
